config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  get "/" => "home#index"

  resources :users
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :due_date, presence: true
  validates :todo_text, length: { minimum: 2 }

  belongs_to :user

  def due_today?
    due_date == Date.today
  end

  def self.of_user(user)
    all.where(user_id: user.id)
  end

  def self.overdue
    where("due_date < ? and completed = ?", Date.today, false)
  end

  def self.due_today
    where(due_date: Date.today)
  end

  def self.due_later
    where("due_date > ?", Date.today)
  end

  def self.completed
    where(completed: true)
  end

  def self.add_task(todo)
    todo_text = todo[:todo_text]
    due_date = Date.today + todo[:due_in_days]
    create!(todo_text: todo_text, due_date: due_date, completed: false)
  end

  def self.mark_as_complete(todo_id)
    todo_for_completion = find(todo_id)
    todo_for_completion.completed = true
    todo_for_completion.save
    return todo_for_completion
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true
  has_secure_password
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Invalid login attemp. Please retry!"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
# todos_conntroller.rb
class TodosController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @todos = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = current_user.todos.find(id)
    render "todo"
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    user_id = current_user.id

    new_todo = Todo.new(todo_text: todo_text,
                        due_date: due_date, completed: false, user_id: user_id)

    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    completed = params[:completed]
    id = params[:id]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = current_user.todos.find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
#users_conntroller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :ensure_user_logged_in

  def create
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    password = params[:password]
    new_user = User.new(first_name: first_name, last_name: last_name,
                        email: email, password: password)

    if new_user.save
      session[:current_user_id] = new_user.id
      redirect_to "/"
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to "/"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="Home-title"> Welcome to the Todo homepage</h1>
<h3 class="Home-authenticate">
  If you are a new user, <%= link_to "sign up here ", new_user_path %>
</h3>
<h3 class="Home-authenticate">
  If you are an existing user, <%= link_to "sign-in here", new_sessions_path %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application',
                            media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if @current_user %>
      <p class="UserHeader">
        Welcome <%= @current_user.first_name%>
        <%= link_to "Sign-out", destroy_session_path, method: "delete"  %>
      </p>
    <%end%>
    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      <%end%>
    </p>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <p class="TodoSectionTitle-text"> <%= section_title %>  </p>
    <p class="TodoSectionTitle-remainingCount"> <%= todos.completed.count %> / <%= todos.count %> </p>
  </div>
  <ul>
    <% todos.each do |todo| %>
      <li class="TodoItem">
        <label class="TodoItem-container">
          <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
            <% check_box_tag("completed", " ", checked = todo.completed,
                class: "TodoItem-checkbox", onclick: "this.form.submit()" ) %>
          <% end %>
          <p class = '<%= todo.completed ? "TodoItem-completedText" : "" %>' >
            <%= todo.todo_text %> </p>
          <% if show_due_date %>
            <p class= "TodoItem-dueDate" >  <%= todo.due_date.to_s(:rfc822) %> </p>
          <% end %>
          <a href="javascript:void(0)" class = "TodoItem-delete">
            <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
              <%= image_submit_tag("delete.png", alt: "Delete") %>
            <% end %>
          </a>
        </label>
      </li>
    <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
<main class="TodoPageMain">
  <article>
    <h1 class="TodoPage-title">My To-do List</h1>
    <%= form_with(url: "/todos", method: "post", class: "AddTodo") do %>
      <%= text_field_tag("todo_text", nil,
                  placeholder: "What's next?", class: "AddTodo-text") %>
      <%= date_field_tag("due_date", nil, class: "AddTodo-date") %>
      <%= submit_tag(value = "Add", class: "AddTodo-button") %>
    <% end %>
    <%= render partial: "todo-section", locals: {
                 section_title: "Overdue",
                 todos: @todos.overdue,
                 show_due_date: true,
               } %>
    <%= render partial: "todo-section", locals: {
                 section_title: "Due Today",
                 todos: @todos.due_today,
                 show_due_date: false,
               } %>
    <%= render partial: "todo-section", locals: {
                 section_title: "Due Later",
                 todos: @todos.due_later,
                 show_due_date: true,
               } %>
  </article>
</main>

app/views/users/new.html.erb
<p class=" Newusers-title">Welcome new user! </p>
<section class = "UsersNew">
  <%= form_with url: users_path do |form| %>
    <div class = "Form-section">
      <p class="FormInput-label">First Name: </p>
      <%= form.text_field :first_name %>

    </div>
    <div class = "Form-section">
      <p class="FormInput-label">Last Name: </p>
      <%= form.text_field :last_name %>
    </div>
    <div class = "Form-section">
      <p class="FormInput-label">email: </p>
      <%= form.email_field :email %>
    </div>
    <div class = "Form-section">
      <p class="FormInput-label">password: </p>
      <%= form.password_field :password %>
    </div>
    <div class = "Form-section">
      <%= form.submit "Sign-up!", class: "Form-submit" %>
    </div>
  <% end %>
</section>